name: Release NuGet Packages

permissions:
  contents: write

on:
  push:
    branches: [ 'main' ]
  
  workflow_dispatch:

jobs:
  
  release:
    uses: ./.github/workflows/release-nuget-package.yml
    with:
      project-path: ${{ matrix.project-path }}
      project-name: ${{ matrix.project-name }}
      dotnet-version: '9.x'
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    strategy:
      matrix:
        include:
          - project-path: 'src/Coderynx.Functional'
            project-name: 'Coderynx.Functional'
          - project-path: 'src/Coderynx.Functional.Orleans'
            project-name: 'Coderynx.Functional.Orleans'
          - project-path: 'src/Coderynx.Functional.WebApi'
            project-name: 'Coderynx.Functional.WebApi'